// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: internal/proto/gophkeeper.proto

// Package proto contains grpc proto files.
package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_internal_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/gophkeeper.proto\x12\n" +
	"gophkeeper\x1a\x19internal/proto/user.proto\x1a\x19internal/proto/file.proto\x1a\x1bgoogle/protobuf/empty.proto2\xcf\x02\n" +
	"\x11GophKeeperService\x122\n" +
	"\bRegister\x12\x0e.user.UserCred\x1a\x16.google.protobuf.Empty\x12/\n" +
	"\x05Login\x12\x0e.user.UserCred\x1a\x16.google.protobuf.Empty\x127\n" +
	"\fGetUserFiles\x12\x16.google.protobuf.Empty\x1a\x0f.file.ListFiles\x126\n" +
	"\n" +
	"UploadFile\x12\x10.file.FileStream\x1a\x14.file.UploadResponse(\x01\x120\n" +
	"\fDownloadFile\x12\f.file.FileId\x1a\x10.file.FileStream0\x01\x122\n" +
	"\n" +
	"DeleteFile\x12\f.file.FileId\x1a\x16.google.protobuf.EmptyB\n" +
	"Z\b./;protob\x06proto3"

var file_internal_proto_gophkeeper_proto_goTypes = []any{
	(*UserCred)(nil),       // 0: user.UserCred
	(*empty.Empty)(nil),    // 1: google.protobuf.Empty
	(*FileStream)(nil),     // 2: file.FileStream
	(*FileId)(nil),         // 3: file.FileId
	(*ListFiles)(nil),      // 4: file.ListFiles
	(*UploadResponse)(nil), // 5: file.UploadResponse
}
var file_internal_proto_gophkeeper_proto_depIdxs = []int32{
	0, // 0: gophkeeper.GophKeeperService.Register:input_type -> user.UserCred
	0, // 1: gophkeeper.GophKeeperService.Login:input_type -> user.UserCred
	1, // 2: gophkeeper.GophKeeperService.GetUserFiles:input_type -> google.protobuf.Empty
	2, // 3: gophkeeper.GophKeeperService.UploadFile:input_type -> file.FileStream
	3, // 4: gophkeeper.GophKeeperService.DownloadFile:input_type -> file.FileId
	3, // 5: gophkeeper.GophKeeperService.DeleteFile:input_type -> file.FileId
	1, // 6: gophkeeper.GophKeeperService.Register:output_type -> google.protobuf.Empty
	1, // 7: gophkeeper.GophKeeperService.Login:output_type -> google.protobuf.Empty
	4, // 8: gophkeeper.GophKeeperService.GetUserFiles:output_type -> file.ListFiles
	5, // 9: gophkeeper.GophKeeperService.UploadFile:output_type -> file.UploadResponse
	2, // 10: gophkeeper.GophKeeperService.DownloadFile:output_type -> file.FileStream
	1, // 11: gophkeeper.GophKeeperService.DeleteFile:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_gophkeeper_proto_init() }
func file_internal_proto_gophkeeper_proto_init() {
	if File_internal_proto_gophkeeper_proto != nil {
		return
	}
	file_internal_proto_user_proto_init()
	file_internal_proto_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gophkeeper_proto_rawDesc), len(file_internal_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_internal_proto_gophkeeper_proto_depIdxs,
	}.Build()
	File_internal_proto_gophkeeper_proto = out.File
	file_internal_proto_gophkeeper_proto_goTypes = nil
	file_internal_proto_gophkeeper_proto_depIdxs = nil
}
