// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: internal/proto/gophkeeper.proto

// Package proto contains grpc proto files.
package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServicePublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePublicKey) Reset() {
	*x = ServicePublicKey{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePublicKey) ProtoMessage() {}

func (x *ServicePublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePublicKey.ProtoReflect.Descriptor instead.
func (*ServicePublicKey) Descriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *ServicePublicKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_internal_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_internal_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/gophkeeper.proto\x12\n" +
	"gophkeeper\x1a\x19internal/proto/user.proto\x1a\x19internal/proto/file.proto\x1a\x1bgoogle/protobuf/empty.proto\"1\n" +
	"\x10ServicePublicKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey2\xdb\x02\n" +
	"\x11GophKeeperService\x128\n" +
	"\bRegister\x12\x0e.user.UserData\x1a\x1c.gophkeeper.ServicePublicKey\x125\n" +
	"\x05Login\x12\x0e.user.UserData\x1a\x1c.gophkeeper.ServicePublicKey\x127\n" +
	"\fGetUserFiles\x12\x16.google.protobuf.Empty\x1a\x0f.file.ListFiles\x126\n" +
	"\n" +
	"UploadFile\x12\x10.file.FileStream\x1a\x14.file.UploadResponse(\x01\x120\n" +
	"\fDownloadFile\x12\f.file.FileId\x1a\x10.file.FileStream0\x01\x122\n" +
	"\n" +
	"DeleteFile\x12\f.file.FileId\x1a\x16.google.protobuf.EmptyB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_internal_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_internal_proto_gophkeeper_proto_rawDescData []byte
)

func file_internal_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_internal_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_internal_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gophkeeper_proto_rawDesc), len(file_internal_proto_gophkeeper_proto_rawDesc)))
	})
	return file_internal_proto_gophkeeper_proto_rawDescData
}

var file_internal_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_gophkeeper_proto_goTypes = []any{
	(*ServicePublicKey)(nil), // 0: gophkeeper.ServicePublicKey
	(*UserData)(nil),         // 1: user.UserData
	(*empty.Empty)(nil),      // 2: google.protobuf.Empty
	(*FileStream)(nil),       // 3: file.FileStream
	(*FileId)(nil),           // 4: file.FileId
	(*ListFiles)(nil),        // 5: file.ListFiles
	(*UploadResponse)(nil),   // 6: file.UploadResponse
}
var file_internal_proto_gophkeeper_proto_depIdxs = []int32{
	1, // 0: gophkeeper.GophKeeperService.Register:input_type -> user.UserData
	1, // 1: gophkeeper.GophKeeperService.Login:input_type -> user.UserData
	2, // 2: gophkeeper.GophKeeperService.GetUserFiles:input_type -> google.protobuf.Empty
	3, // 3: gophkeeper.GophKeeperService.UploadFile:input_type -> file.FileStream
	4, // 4: gophkeeper.GophKeeperService.DownloadFile:input_type -> file.FileId
	4, // 5: gophkeeper.GophKeeperService.DeleteFile:input_type -> file.FileId
	0, // 6: gophkeeper.GophKeeperService.Register:output_type -> gophkeeper.ServicePublicKey
	0, // 7: gophkeeper.GophKeeperService.Login:output_type -> gophkeeper.ServicePublicKey
	5, // 8: gophkeeper.GophKeeperService.GetUserFiles:output_type -> file.ListFiles
	6, // 9: gophkeeper.GophKeeperService.UploadFile:output_type -> file.UploadResponse
	3, // 10: gophkeeper.GophKeeperService.DownloadFile:output_type -> file.FileStream
	2, // 11: gophkeeper.GophKeeperService.DeleteFile:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_gophkeeper_proto_init() }
func file_internal_proto_gophkeeper_proto_init() {
	if File_internal_proto_gophkeeper_proto != nil {
		return
	}
	file_internal_proto_user_proto_init()
	file_internal_proto_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gophkeeper_proto_rawDesc), len(file_internal_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_internal_proto_gophkeeper_proto_depIdxs,
		MessageInfos:      file_internal_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_internal_proto_gophkeeper_proto = out.File
	file_internal_proto_gophkeeper_proto_goTypes = nil
	file_internal_proto_gophkeeper_proto_depIdxs = nil
}
